# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: 'Acceptance'

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}--${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

  debug:
    name: 'Debug test'
    runs-on: 'ubuntu-latest'

    steps:

      - name: 'Debug'
        run: |
          echo "Passed."
