name: 'Commit'

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}--${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  debug:
    name: 'Debug Job'
    runs-on: 'ubuntu-latest'
    steps:

        - name: 'Debug Output'
          run: |
             echo "Job: Debug Job, Step: Debug Output" 

  unit:
    name: 'PHP Unit Tests'
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        php-version:
          - '8.1'

    steps:

      - name: 'Debug Output'
        run: |
          echo "Job: Unit, Step: Debug Output" 
          
  security:
    name: 'PHP Security Analysis'
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        php-version:
          - '8.1'

    steps:

      - name: 'Debug Output'
        run: |
          echo "Job: PHP Security Analysis, Step: Debug Output"
