name: 'Commit'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}--${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

  compile:
    name: 'Compile'
    runs-on: 'ubuntu-latest'
    steps:

        - name: 'Debug Output'
          run: |
             echo "Job: Debug Job, Step: Debug Output" 

  unit:
    name: 'PHP Unit Tests'
    runs-on: 'ubuntu-latest'
    needs:
      - compile

    strategy:
      matrix:
        php-version:
          - '8.1'

    steps:

      - name: 'Debug Output'
        run: |
          echo "Job: Unit, Step: Debug Output" 
          
  security:
    name: 'PHP Security Analysis'
    runs-on: 'ubuntu-latest'
    needs:
      - compile

    strategy:
      matrix:
        php-version:
          - '8.1'

    steps:

      - name: 'Debug Output'
        run: |
          echo "Job: PHP Security Analysis, Step: Debug Output"

  static:
    name: 'PHP Static Analysis'
    runs-on: 'ubuntu-latest'
    needs:
      - compile

    strategy:
      matrix:
        php-version:
          - '8.1'

    steps:

      - name: 'Debug Output'
        run: |
          echo "Job: PHP Static Analysis, Step: Debug Output"

  acceptance:
    name: 'Acceptance'
    runs-on: 'ubuntu-latest'
    needs:
      - unit
      - security
      - static
    
    steps:

      - name: 'Debug'
        run: |
          echo "Passed."
          
