# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: 'Dependabot Auto Merge Pull Request'

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'Acceptance'
    types:
      - completed
    branches:
      - 'dependabot/**'

permissions:
  pull-requests: write
  contents: write

jobs:

  # Auto Merge Pull Request.
  #
  # Performs the following steps:
  # - Generate GitHub token from GitHub App (Bot)
  # - Auto Approve Pull Request
  # - Auto Merges Pull Request
  # - Post Slack notification message

  auto-merge-pr:

    runs-on: ubuntu-latest

    # Only run if the creator is Dependabot.
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: "Determine pull request number"
        uses: "actions/github-script@v6.4.1"
        with:
          github-token: ${{ github.token }}
          script: |
            if (
              context.eventName == 'pull_request' ||
              context.eventName == 'pull_request_target'
            ) {
              core.exportVariable("PULL_REQUEST_NUMBER", context.payload.pull_request.number);
              return;
            }

            if (context.eventName == 'workflow_run') {
              core.exportVariable("PULL_REQUEST_NUMBER", context.payload.workflow_run.pull_requests[0].number);
              return;
            }

            core.setFailed(`Unable to determine the pull request number for event "${context.eventName}"`);

      # - name: 'Fetch Dependabot metadata.'
      #   id: dependabot-metadata
      #   uses: dependabot/fetch-metadata@v1.6.0
      #   with:
      #     # alert-lookup: true
      #     # compat-lookup: true
      #     github-token: "${{ github.token }}"

      - name: "Logs debug information."
        run: |
          echo "Debug."
          # echo ${{ env.PULL_REQUEST_NUMBER }}
          # echo ${{ steps.dependabot-metadata.outputs.update-type }}
