# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Deploy"

on:
  workflow_run:
    workflows:
      - 'Commit'
    types:
      - completed
    branches:
      - 'main'
      - 'trunk'

  workflow_dispatch:

jobs:

  deploy:

    if: github.event.workflow_run.conclusion == 'success'
  
    name: "Compile project."
    runs-on: "ubuntu-latest"

    steps:

      - name: 'Debug.'
        run: |
          echo "Deploy project."
